/// Reagent calibration series, loaded from the shared golden-vector file.
///
/// The calibration numbers are **not** duplicated in Dart source. They are read
/// from `assets/calibration/golden_vectors.json`, which is generated by
/// `backend/scripts/generate_golden_vectors.py` from the Python reference
/// tables. Hard-coding them here would create a second source of truth that
/// drifts the first time someone adds a reagent, and the handset would then be
/// running different chemistry from the server without anybody noticing.
library;

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/services.dart' show rootBundle;

import 'color_math.dart';

class CalibrationStop {
  const CalibrationStop({
    required this.concentration,
    required this.lab,
    this.label,
  });

  final double concentration;
  final Lab lab;
  final String? label;
}

class CalibrationSeries {
  const CalibrationSeries({
    required this.assay,
    required this.calibrationId,
    required this.displayName,
    required this.unit,
    required this.stops,
    required this.actionThreshold,
    required this.reagentRepeatabilityDe,
    required this.maxOffPathDe,
    required this.isLabValidated,
    required this.supportedCrops,
  });

  final String assay;
  final String calibrationId;
  final String displayName;
  final String unit;
  final List<CalibrationStop> stops;
  final double actionThreshold;

  /// How much two identical strips at the same concentration differ. Combined
  /// with the optical correction residual to form the reported interval.
  final double reagentRepeatabilityDe;

  /// How far off the calibration path a colour may sit before we conclude the
  /// thing being measured is not this reagent at all.
  final double maxOffPathDe;

  /// False for every series shipped in this build: these are provisional
  /// engineering calibrations awaiting NABL validation.
  final bool isLabValidated;

  final List<String> supportedCrops;

  double get lowestConcentration => stops.first.concentration;

  double get highestConcentration => stops.last.concentration;

  /// Human-facing band. Deliberately plain language, never a verdict.
  String bandLabel(double concentration) {
    String? label;
    for (final CalibrationStop stop in stops) {
      if (stop.concentration <= concentration && stop.label != null) {
        label = stop.label;
      }
    }
    return label ?? stops.first.label ?? 'below lowest stop';
  }

  factory CalibrationSeries.fromJson(String assay, Map<String, dynamic> json) {
    return CalibrationSeries(
      assay: assay,
      calibrationId: json['calibration_id'] as String,
      displayName: json['display_name'] as String? ?? assay,
      unit: json['unit'] as String,
      actionThreshold: (json['action_threshold'] as num).toDouble(),
      reagentRepeatabilityDe: (json['reagent_repeatability_de'] as num).toDouble(),
      maxOffPathDe: (json['max_off_path_de'] as num).toDouble(),
      isLabValidated: json['is_lab_validated'] as bool? ?? false,
      supportedCrops:
          (json['supported_crops'] as List<dynamic>? ?? <dynamic>[]).cast<String>(),
      stops: (json['stops'] as List<dynamic>)
          .map((dynamic raw) {
            final Map<String, dynamic> stop = raw as Map<String, dynamic>;
            final List<dynamic> lab = stop['lab'] as List<dynamic>;
            return CalibrationStop(
              concentration: (stop['concentration'] as num).toDouble(),
              lab: Lab(
                (lab[0] as num).toDouble(),
                (lab[1] as num).toDouble(),
                (lab[2] as num).toDouble(),
              ),
              label: stop['label'] as String?,
            );
          })
          .toList(growable: false),
    );
  }
}

/// Where a measured colour sits on a calibration path.
class PathProjection {
  const PathProjection({
    required this.concentration,
    required this.offPathDe,
    required this.nearestStopDe,
    required this.segmentIndex,
    required this.segmentFraction,
    required this.localSensitivity,
  });

  final double concentration;
  final double offPathDe;
  final double nearestStopDe;
  final int segmentIndex;
  final double segmentFraction;

  /// Concentration units per unit of Lab distance, at this point on the path.
  final double localSensitivity;
}

class CalibrationRegistry {
  CalibrationRegistry._(this._series);

  final Map<String, CalibrationSeries> _series;

  static CalibrationRegistry? _instance;

  static CalibrationRegistry get instance {
    final CalibrationRegistry? registry = _instance;
    if (registry == null) {
      throw StateError(
        'CalibrationRegistry.load() must be awaited before the registry is used.',
      );
    }
    return registry;
  }

  static bool get isLoaded => _instance != null;

  static Future<CalibrationRegistry> load({
    String assetPath = 'assets/calibration/golden_vectors.json',
  }) async {
    final String raw = await rootBundle.loadString(assetPath);
    final Map<String, dynamic> json = jsonDecode(raw) as Map<String, dynamic>;
    final Map<String, dynamic> calibrations =
        json['calibrations'] as Map<String, dynamic>;

    final Map<String, CalibrationSeries> series = <String, CalibrationSeries>{};
    calibrations.forEach((String assay, dynamic value) {
      series[assay] = CalibrationSeries.fromJson(
        assay,
        value as Map<String, dynamic>,
      );
    });

    _instance = CalibrationRegistry._(series);
    return _instance!;
  }

  /// Test seam: build a registry from a decoded map without touching assets.
  static CalibrationRegistry fromMap(Map<String, dynamic> calibrations) {
    final Map<String, CalibrationSeries> series = <String, CalibrationSeries>{};
    calibrations.forEach((String assay, dynamic value) {
      series[assay] = CalibrationSeries.fromJson(
        assay,
        value as Map<String, dynamic>,
      );
    });
    _instance = CalibrationRegistry._(series);
    return _instance!;
  }

  /// Returns null for an unknown reagent rather than a default. Guessing which
  /// chemistry the user meant would be worse than refusing.
  CalibrationSeries? operator [](String assay) => _series[assay];

  Iterable<CalibrationSeries> get all => _series.values;

  List<String> get assays => _series.keys.toList(growable: false);
}

/// Project a point onto a line segment. Returns (t in [0,1], distance).
({double t, double distance}) _projectOntoSegment(Lab point, Lab a, Lab b) {
  final Lab ab = b - a;
  final double denominator = ab.l * ab.l + ab.a * ab.a + ab.b * ab.b;
  if (denominator < 1e-12) {
    return (t: 0.0, distance: point.distanceTo(a));
  }
  final Lab ap = point - a;
  final double raw = (ap.l * ab.l + ap.a * ab.a + ap.b * ab.b) / denominator;
  final double t = raw.clamp(0.0, 1.0).toDouble();
  return (t: t, distance: point.distanceTo(a + ab * t));
}

/// Locate a corrected strip colour along a calibration series.
///
/// Projection is a Euclidean geometry problem in Lab (finding the closest point
/// on a polyline), while the *reported* distances use CIEDE2000. Mixing the two
/// is deliberate: CIEDE2000 is not a metric and does not admit a well-defined
/// projection, but it is the right measure for "how different do these look",
/// which is what the off-path and nearest-stop diagnostics mean.
PathProjection projectOntoPath(Lab point, CalibrationSeries series) {
  int bestIndex = 0;
  double bestT = 0.0;
  double bestDistance = double.infinity;

  for (int i = 0; i < series.stops.length - 1; i++) {
    final result = _projectOntoSegment(
      point,
      series.stops[i].lab,
      series.stops[i + 1].lab,
    );
    if (result.distance < bestDistance) {
      bestIndex = i;
      bestT = result.t;
      bestDistance = result.distance;
    }
  }

  final double loC = series.stops[bestIndex].concentration;
  final double hiC = series.stops[bestIndex + 1].concentration;
  final double concentration = loC + bestT * (hiC - loC);

  final Lab segmentStart = series.stops[bestIndex].lab;
  final Lab segmentEnd = series.stops[bestIndex + 1].lab;
  final double segmentLength = segmentStart.distanceTo(segmentEnd);
  final double sensitivity =
      segmentLength > 1e-9 ? (hiC - loC) / segmentLength : 0.0;

  final Lab foot = segmentStart + (segmentEnd - segmentStart) * bestT;
  final double offPath = deltaE2000(point, foot);

  double nearestStop = double.infinity;
  for (final CalibrationStop stop in series.stops) {
    final double d = deltaE2000(point, stop.lab);
    if (d < nearestStop) nearestStop = d;
  }

  return PathProjection(
    concentration: concentration,
    offPathDe: offPath,
    nearestStopDe: nearestStop,
    segmentIndex: bestIndex,
    segmentFraction: bestT,
    localSensitivity: sensitivity,
  );
}

/// Turn colour-space uncertainty into a concentration interval.
///
/// Two independent error sources combined in quadrature: the optical
/// uncertainty from the leave-one-out correction residual, and the reagent's
/// own repeatability. The result is mapped to concentration through the local
/// slope of the calibration path, then clamped to the calibrated range —
/// extrapolating past an end stop would be guessing.
({double low, double high}) confidenceInterval(
  PathProjection projection,
  CalibrationSeries series,
  double opticalUncertaintyDe,
) {
  final double optical = opticalUncertaintyDe < 0 ? 0 : opticalUncertaintyDe;
  final double combined = _hypot(optical, series.reagentRepeatabilityDe);
  final double halfWidth = combined * projection.localSensitivity.abs();

  final double low =
      (projection.concentration - halfWidth).clamp(series.lowestConcentration, double.infinity);
  final double high =
      (projection.concentration + halfWidth).clamp(double.negativeInfinity, series.highestConcentration);

  return (
    low: double.parse(low.toStringAsFixed(4)),
    high: double.parse(high.toStringAsFixed(4)),
  );
}

/// Euclidean combination of two independent uncertainties.
double _hypot(double a, double b) => math.sqrt(a * a + b * b);
