"""The SATVA reference card: its printed specification and its detection.

Why a card at all
-----------------
A phone camera does not measure colour; it measures whatever its auto-exposure
and auto-white-balance decided to produce under a market stall's mixed
fluorescent/daylight illumination. A reading taken without a known reference is
therefore not a measurement at all. Spec 7 makes the card mandatory, and
non-negotiable rule 3 makes its absence a refusal rather than a low-confidence
result.

Card geometry (v1)
------------------
Credit-card sized, 85.6 x 54.0 mm, printed on matte stock to suppress specular
highlights. Layout in normalised card coordinates (0,0 top-left, 1,1
bottom-right):

    +--------------------------------------------------+
    | [K] N0  N1  N2  N3  N4  N5                       |   neutral ramp
    |                                    +-----------+ |
    |  C0  C1  C2  C3  C4  C5            | STRIP WELL| |
    |                                    +-----------+ |
    +--------------------------------------------------+

* ``[K]`` is a saturated blue orientation key in the top-left corner. It breaks
  the card's rotational symmetry so a card photographed upside-down is
  re-oriented rather than misread.
* The neutral ramp drives exposure checking and the grey-world/illuminant
  estimate.
* The chromatic patches constrain the colour-correction fit; without chromatic
  constraints a per-channel gain fit is under-determined for tinted illuminants.
* The strip well is a printed aperture. The user lays the reacted strip inside
  it, which guarantees the strip and the reference patches share one
  illumination field and one exposure.

A printable PDF/SVG of this exact specification is generated by
``scripts/generate_reference_card.py`` so the numbers here and the numbers on
paper cannot drift apart.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import cv2
import numpy as np

from app.services.colorimetry.color_math import srgb_u8_to_lab

CARD_WIDTH_MM = 85.6
CARD_HEIGHT_MM = 54.0
CARD_ASPECT = CARD_WIDTH_MM / CARD_HEIGHT_MM

# Canonical warp size. 100 px per 10 mm gives ~34 px patches, enough pixels for
# a stable mean while keeping the warp cheap on a low-end handset.
WARP_WIDTH = 856
WARP_HEIGHT = 540


@dataclass(frozen=True)
class Patch:
    """One printed colour patch.

    ``rect`` is (x, y, w, h) in normalised card coordinates. ``srgb`` is the
    value the patch is printed to, as 8-bit sRGB, measured off the reference
    print run rather than taken from the design file.
    """

    name: str
    rect: tuple[float, float, float, float]
    srgb: tuple[int, int, int]
    is_neutral: bool = False

    def pixel_rect(
        self, width: int = WARP_WIDTH, height: int = WARP_HEIGHT
    ) -> tuple[int, int, int, int]:
        x, y, w, h = self.rect
        return (int(x * width), int(y * height), int(w * width), int(h * height))

    @property
    def lab(self) -> np.ndarray:
        return srgb_u8_to_lab(np.array(self.srgb, dtype=np.float64))


@dataclass(frozen=True)
class ReferenceCardSpec:
    card_id: str
    version: str
    patches: tuple[Patch, ...]
    strip_well: tuple[float, float, float, float]
    orientation_key: Patch
    border_mm: float = 4.0

    @property
    def neutral_patches(self) -> list[Patch]:
        return [p for p in self.patches if p.is_neutral]

    @property
    def chromatic_patches(self) -> list[Patch]:
        return [p for p in self.patches if not p.is_neutral]

    def patch_by_name(self, name: str) -> Patch:
        for p in self.patches:
            if p.name == name:
                return p
        raise KeyError(name)


def _row(
    prefix: str,
    y: float,
    values: list[tuple[int, int, int]],
    *,
    x0: float,
    neutral: bool,
    patch_w: float = 0.085,
    patch_h: float = 0.26,
    gap: float = 0.015,
) -> list[Patch]:
    out: list[Patch] = []
    for i, srgb in enumerate(values):
        x = x0 + i * (patch_w + gap)
        out.append(Patch(f"{prefix}{i}", (x, y, patch_w, patch_h), srgb, neutral))
    return out


# Neutral ramp: six steps chosen to span the exposure range without clipping at
# either end. Nothing is printed at 255 or 0, because a clipped reference patch
# carries no information about how badly the frame is clipped.
_NEUTRALS: list[tuple[int, int, int]] = [
    (243, 243, 242),
    (200, 200, 200),
    (160, 160, 160),
    (122, 122, 121),
    (85, 85, 85),
    (52, 52, 52),
]

# Chromatic patches. Values follow the widely published ColorChecker sRGB
# renderings for hues that bracket the turmeric-indicator reaction path
# (yellow -> orange -> red-brown), plus green and blue anchors so the fit is
# constrained across the whole gamut rather than only along the reaction path.
_CHROMATICS: list[tuple[int, int, int]] = [
    (222, 118, 32),
    (231, 199, 31),
    (187, 86, 149),
    (98, 122, 157),
    (87, 108, 67),
    (170, 65, 51),
]

_ORIENTATION_KEY = Patch("KEY", (0.020, 0.060, 0.060, 0.14), (24, 58, 168), False)

SATVA_CARD_V1 = ReferenceCardSpec(
    card_id="satva-refcard",
    version="v1",
    orientation_key=_ORIENTATION_KEY,
    patches=tuple(
        _row("N", 0.075, _NEUTRALS, x0=0.100, neutral=True, patch_h=0.24)
        + _row("C", 0.400, _CHROMATICS, x0=0.100, neutral=False, patch_h=0.24)
    ),
    # Strip well sits in the lower band, clear of both patch rows.
    strip_well=(0.180, 0.700, 0.560, 0.200),
)


@dataclass
class CardDetection:
    """Result of locating the card in a frame."""

    found: bool
    warped: np.ndarray | None = None
    corners: np.ndarray | None = None
    quad_area_fraction: float = 0.0
    orientation_confidence: float = 0.0
    reason: str | None = None
    diagnostics: dict = field(default_factory=dict)


def _order_corners(pts: np.ndarray) -> np.ndarray:
    """Order four points as top-left, top-right, bottom-right, bottom-left."""
    pts = pts.reshape(4, 2).astype(np.float64)
    s = pts.sum(axis=1)
    diff = np.diff(pts, axis=1).ravel()
    return np.array(
        [
            pts[np.argmin(s)],
            pts[np.argmin(diff)],
            pts[np.argmax(s)],
            pts[np.argmax(diff)],
        ],
        dtype=np.float32,
    )


def _candidate_quads(gray: np.ndarray) -> list[np.ndarray]:
    """Find plausible card outlines.

    Two passes are used because market lighting is unreliable: adaptive
    thresholding handles uneven illumination across the card, while Canny
    handles low-contrast backgrounds where the card edge is a soft gradient.
    """
    quads: list[np.ndarray] = []
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    binaries = [
        cv2.adaptiveThreshold(
            blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 31, 8
        ),
        cv2.dilate(cv2.Canny(blurred, 40, 140), np.ones((3, 3), np.uint8), iterations=1),
    ]

    image_area = float(gray.shape[0] * gray.shape[1])
    for binary in binaries:
        contours, _ = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
        for contour in contours:
            area = cv2.contourArea(contour)
            if area < 0.02 * image_area:
                continue
            peri = cv2.arcLength(contour, True)
            approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
            if len(approx) != 4 or not cv2.isContourConvex(approx):
                continue
            ordered = _order_corners(approx)
            w = max(
                np.linalg.norm(ordered[1] - ordered[0]),
                np.linalg.norm(ordered[2] - ordered[3]),
            )
            h = max(
                np.linalg.norm(ordered[3] - ordered[0]),
                np.linalg.norm(ordered[2] - ordered[1]),
            )
            if h <= 1:
                continue
            aspect = w / h
            # Allow a generous aspect band: the card is usually photographed at
            # an angle, and perspective compresses one axis.
            if not (0.70 * CARD_ASPECT <= aspect <= 1.45 * CARD_ASPECT):
                continue
            quads.append(ordered)
    return quads


def _score_orientation(warped: np.ndarray, spec: ReferenceCardSpec) -> float:
    """How well does the orientation key match blue at the expected corner?"""
    x, y, w, h = spec.orientation_key.pixel_rect()
    block = warped[y : y + h, x : x + w]
    if block.size == 0:
        return 0.0
    mean_bgr = block.reshape(-1, 3).mean(axis=0)
    b, g, r = mean_bgr
    # Blue-dominance score in [0, 1]; robust to overall exposure.
    total = float(b + g + r) + 1e-6
    return float(np.clip((b - max(g, r)) / total * 3.0, 0.0, 1.0))


def detect_card(image_bgr: np.ndarray, spec: ReferenceCardSpec = SATVA_CARD_V1) -> CardDetection:
    """Locate and rectify the reference card.

    Returns a detection with ``found=False`` and a ``reason`` rather than
    raising, because "no card" is an expected, first-class outcome that the UI
    must be able to explain to the user.
    """
    if image_bgr is None or image_bgr.size == 0:
        return CardDetection(False, reason="empty_image")

    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    quads = _candidate_quads(gray)
    if not quads:
        return CardDetection(False, reason="no_quadrilateral_found")

    image_area = float(gray.shape[0] * gray.shape[1])
    target = np.array(
        [[0, 0], [WARP_WIDTH - 1, 0], [WARP_WIDTH - 1, WARP_HEIGHT - 1], [0, WARP_HEIGHT - 1]],
        dtype=np.float32,
    )

    best: CardDetection | None = None
    for quad in sorted(quads, key=lambda q: -cv2.contourArea(q)):
        for rotation in range(4):
            rotated = np.roll(quad, -rotation, axis=0).astype(np.float32)
            matrix = cv2.getPerspectiveTransform(rotated, target)
            warped = cv2.warpPerspective(image_bgr, matrix, (WARP_WIDTH, WARP_HEIGHT))
            score = _score_orientation(warped, spec)
            if best is None or score > best.orientation_confidence:
                best = CardDetection(
                    found=True,
                    warped=warped,
                    corners=rotated,
                    quad_area_fraction=float(cv2.contourArea(quad) / image_area),
                    orientation_confidence=score,
                    diagnostics={"candidate_quads": len(quads), "rotation": rotation},
                )
        # The largest valid quad wins; no need to evaluate smaller candidates
        # once one of them has produced a confident orientation.
        if best is not None and best.orientation_confidence >= 0.35:
            break

    if best is None:
        return CardDetection(False, reason="no_quadrilateral_found")

    if best.orientation_confidence < 0.18:
        # A quadrilateral was found but it does not look like a SATVA card.
        return CardDetection(
            False,
            reason="orientation_key_not_found",
            quad_area_fraction=best.quad_area_fraction,
            orientation_confidence=best.orientation_confidence,
            diagnostics=best.diagnostics,
        )

    if best.quad_area_fraction < 0.04:
        return CardDetection(
            False,
            reason="card_too_small_in_frame",
            quad_area_fraction=best.quad_area_fraction,
            diagnostics=best.diagnostics,
        )

    return best


def sample_patch(warped_bgr: np.ndarray, patch: Patch, *, inset: float = 0.22) -> np.ndarray:
    """Mean 8-bit RGB of a patch, sampled from its centre.

    The inset discards the outer band of each patch so that print registration
    error, a slight homography error, or ink bleed at the patch edge cannot pull
    the mean. Returned as RGB (not OpenCV's BGR) to match the colour maths.
    """
    x, y, w, h = patch.pixel_rect()
    dx, dy = int(w * inset), int(h * inset)
    block = warped_bgr[y + dy : y + h - dy, x + dx : x + w - dx]
    if block.size == 0:
        return np.array([0.0, 0.0, 0.0])
    mean_bgr = block.reshape(-1, 3).astype(np.float64).mean(axis=0)
    return mean_bgr[::-1]


def sample_patch_pixels(
    warped_bgr: np.ndarray,
    rect: tuple[float, float, float, float],
    *,
    inset: float = 0.12,
) -> np.ndarray:
    """All RGB pixels inside a normalised rect, as an (N, 3) array."""
    x = int(rect[0] * WARP_WIDTH)
    y = int(rect[1] * WARP_HEIGHT)
    w = int(rect[2] * WARP_WIDTH)
    h = int(rect[3] * WARP_HEIGHT)
    dx, dy = int(w * inset), int(h * inset)
    block = warped_bgr[y + dy : y + h - dy, x + dx : x + w - dx]
    if block.size == 0:
        return np.zeros((0, 3))
    return block.reshape(-1, 3)[:, ::-1].astype(np.float64)
